[tool.poetry]
name = "rusty_log_parser"
version = "0.1.0"
description = "Log file parser with Rust core"
authors = ["Pavel Kirilin <win10@list.ru>"]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
